ALTER TABLE users
  ADD COLUMN IF NOT EXISTS weather_city TEXT;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS weather_lat DOUBLE PRECISION;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS weather_lon DOUBLE PRECISION;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS last_presence_at TIMESTAMPTZ;
